# Generated by Django 4.0.2 on 2022-02-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_ingredientlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientlist',
            name='recipe',
            field=models.CharField(default='Recipe_Placeholder', max_length=850),
            preserve_default=False,
        ),
    ]
