# Generated by Django 4.0.2 on 2022-03-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_generator', '0002_ingredientlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientlist',
            name='output_ingredients',
            field=models.CharField(default='ing_Placeholder', max_length=850),
        ),
        migrations.AddField(
            model_name='ingredientlist',
            name='output_steps',
            field=models.CharField(default='steps_Placeholder', max_length=850),
        ),
    ]
