# Generated by Django 4.0.2 on 2022-03-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_generator', '0003_ingredientlist_output_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientlist',
            name='output_ingredients',
            field=models.TextField(default='ing_Placeholder'),
        ),
        migrations.AlterField(
            model_name='ingredientlist',
            name='output_steps',
            field=models.TextField(default='steps_Placeholder'),
        ),
        migrations.AlterField(
            model_name='ingredientlist',
            name='recipe',
            field=models.TextField(default='Recipe_Placeholder'),
        ),
    ]
